---
- name: install docker
  hosts: web
  become: true
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
- name: docker local
  hosts: localhost
  become: true
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
# install docker on web and localhost
